FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# HUBusivi

Progetto Ingegneria Del Software 2 - Università degli studi di Trento

### Log-in [GET]

Inserire i dati per effettuare il login. Verrà eseguito l'accesso con le relative opportunità.

+ Request (application/json)

        {
            "username": "aaa@mail.com",
            "password": "abcd1234"
        }
        
##Assignment [/assig]

###Create assignment [POST]

Creazione assignment da parte dell'insegnante che poi gli studenti dovranno eseguire

###Updating assignment []

###Removing assignment []

##Compiti [/comp]

###Create compiti []

###Updating compiti []

###Removing compiti []

##Voti

###Aggiungi voto

###Rimuovi voto

###Modifica voto

###Media voti